server:
  address: 0.0.0.0
  port: 8086

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0
          jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
          audiences:
            - 2f01f2a9-d3f9-4275-971d-9581d37c1d9d
            - api://2f01f2a9-d3f9-4275-971d-9581d37c1d9d

springdoc:
  swagger-ui:
    path: /api-locations.html
  api-docs:
    path: /api-locations

firebase:
  project-id: ${FIREBASE_PROJECT_ID}
  private-key: ${FIREBASE_PRIVATE_KEY}
  private-key-id: ${FIREBASE_PRIVATE_KEY_ID}
  client-email: ${FIREBASE_CLIENT_EMAIL}
  client-id: ${FIREBASE_CLIENT_ID}
  auth-uri: ${FIREBASE_AUTH_URI}
  token-uri: ${FIREBASE_TOKEN_URI}
  auth-provider-x509-cert-url: ${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
  client-x509-cert-url: ${FIREBASE_CLIENT_X509_CERT_URL}
  universe-domain: ${FIREBASE_UNIVERSE_DOMAIN}

